// This file is @generated by prost-build.
/// EventStreamMessage is the union type for all messages exchanged
/// between the Master and a Worker in both directions (symmetric).
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventStreamMessage {
    /// A unique identifier for the event, used for logging and correlation.
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    /// Tenant and Worker IDs provide context for the event.
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(oneof = "event_stream_message::Payload", tags = "4, 5, 6, 7, 8")]
    pub payload: ::core::option::Option<event_stream_message::Payload>,
}
/// Nested message and enum types in `EventStreamMessage`.
pub mod event_stream_message {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// ---- Events initiated by the Worker ----
        #[prost(message, tag = "4")]
        RegisterEvent(super::RegisterEvent),
        #[prost(message, tag = "5")]
        HeartbeatEvent(super::HeartbeatEvent),
        #[prost(message, tag = "6")]
        DataPullStatusUpdate(super::DataPullStatusUpdateEvent),
        /// ---- Events initiated by the Master ----
        #[prost(message, tag = "7")]
        DataAssignment(super::DataAssignmentEvent),
        /// ---- Common Events (bidirectional) ----
        /// Used for acknowledgments, control commands, and other flexible message types
        #[prost(message, tag = "8")]
        CommonAck(super::CommonAckEvent),
    }
}
/// CommonAckEvent is a unified event type for acknowledgments and control messages.
/// It replaces specific event types like RegistrationAckEvent, HeartbeatAckEvent, etc.
/// with a flexible structure that can represent any acknowledgment or control command.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonAckEvent {
    /// The server ID of the node sending this acknowledgment
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// The type of event being acknowledged or the command being sent
    /// Examples: "registration_ack", "heartbeat_ack", "evict_epoch", "drain_command"
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// Flexible payload containing event-specific data
    /// For registration_ack: may contain heartbeat_interval_seconds, accepted status
    /// For heartbeat_ack: may contain drain command
    /// For evict_epoch: may contain dataset_id, epoch_id, reason
    #[prost(message, optional, tag = "3")]
    pub payload: ::core::option::Option<super::google::protobuf::Struct>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Worker {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub addr: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterEvent {
    #[prost(message, optional, tag = "1")]
    pub worker: ::core::option::Option<Worker>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatEvent {}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataPullStatusUpdateEvent {
    #[prost(string, tag = "1")]
    pub dataset_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub epoch_id: ::prost::alloc::string::String,
    #[prost(enumeration = "data_pull_status_update_event::Status", tag = "3")]
    pub status: i32,
    /// Populated if status is FAILED.
    #[prost(string, tag = "4")]
    pub error_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `DataPullStatusUpdateEvent`.
pub mod data_pull_status_update_event {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unknown = 0,
        InProgress = 1,
        Completed = 2,
        Failed = 3,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::InProgress => "IN_PROGRESS",
                Self::Completed => "COMPLETED",
                Self::Failed => "FAILED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "IN_PROGRESS" => Some(Self::InProgress),
                "COMPLETED" => Some(Self::Completed),
                "FAILED" => Some(Self::Failed),
                _ => None,
            }
        }
    }
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataAssignmentEvent {
    #[prost(string, tag = "1")]
    pub dataset_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub epoch_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub load_plan: ::core::option::Option<LoadPlan>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadPlan {
    #[prost(string, tag = "1")]
    pub plan_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<super::common::DataSource>,
    /// The table name in DuckDB following the pattern: {dataset_id}__{epoch_id}
    /// Example: "sales_data__1730419200000_a7b3c2"
    /// This establishes the 1:1 relationship: one epoch_id = one DuckDB table
    #[prost(string, tag = "3")]
    pub destination_table_name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub arrow_schema: ::prost::alloc::vec::Vec<u8>,
    /// REQUIRED: Resolved partition information for this specific epoch
    /// This tells the Worker exactly what time range and partition values
    /// this epoch represents, enabling it to generate the optimized table macro
    #[prost(message, optional, tag = "5")]
    pub resolved_partition: ::core::option::Option<ResolvedPartition>,
}
/// The concrete partition values for a single epoch
/// This is what the Worker needs to generate the table macro constants
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResolvedPartition {
    /// The time range this epoch represents (REQUIRED)
    /// Used in macro: WHERE (DATE 'start' >= start_dt AND DATE 'start' < end_excl)
    #[prost(message, optional, tag = "1")]
    pub time_range: ::core::option::Option<super::common::TimeRange>,
    /// The name of the time partition column in the loaded data
    /// Used in macro: AND dt = DATE '2025-10-25'
    #[prost(string, tag = "2")]
    pub time_column_name: ::prost::alloc::string::String,
    /// The specific time partition value(s) this epoch contains
    /// For single partition: "2025-10-25"
    /// For coalesced epochs: start date of the range
    #[prost(string, tag = "3")]
    pub time_partition_value: ::prost::alloc::string::String,
    /// Additional dimension partition values (if multi-dimensional)
    #[prost(map = "string, string", tag = "4")]
    pub dimension_values: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// DEPRECATED: EventResponse is being phased out in favor of CommonAckEvent within EventStreamMessage
/// for symmetric bidirectional communication. Kept temporarily for backward compatibility.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventResponse {
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::ResponseStatus", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub payload: ::core::option::Option<super::google::protobuf::Struct>,
}
/// Generated client implementations.
pub mod control_plane_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ControlPlaneService defines the bidirectional stream for all real-time
    /// communication between a Worker and the Master.
    /// The stream is now symmetric - both sides send and receive EventStreamMessage.
    #[derive(Debug, Clone)]
    pub struct ControlPlaneServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ControlPlaneServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ControlPlaneServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ControlPlaneServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ControlPlaneServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn coordinate_worker(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::EventStreamMessage,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::EventStreamMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/control_plane.ControlPlaneService/CoordinateWorker",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "control_plane.ControlPlaneService",
                        "CoordinateWorker",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod control_plane_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ControlPlaneServiceServer.
    #[async_trait]
    pub trait ControlPlaneService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the CoordinateWorker method.
        type CoordinateWorkerStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::EventStreamMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn coordinate_worker(
            &self,
            request: tonic::Request<tonic::Streaming<super::EventStreamMessage>>,
        ) -> std::result::Result<
            tonic::Response<Self::CoordinateWorkerStream>,
            tonic::Status,
        >;
    }
    /// ControlPlaneService defines the bidirectional stream for all real-time
    /// communication between a Worker and the Master.
    /// The stream is now symmetric - both sides send and receive EventStreamMessage.
    #[derive(Debug)]
    pub struct ControlPlaneServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ControlPlaneServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ControlPlaneServiceServer<T>
    where
        T: ControlPlaneService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/control_plane.ControlPlaneService/CoordinateWorker" => {
                    #[allow(non_camel_case_types)]
                    struct CoordinateWorkerSvc<T: ControlPlaneService>(pub Arc<T>);
                    impl<
                        T: ControlPlaneService,
                    > tonic::server::StreamingService<super::EventStreamMessage>
                    for CoordinateWorkerSvc<T> {
                        type Response = super::EventStreamMessage;
                        type ResponseStream = T::CoordinateWorkerStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::EventStreamMessage>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ControlPlaneService>::coordinate_worker(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CoordinateWorkerSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ControlPlaneServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "control_plane.ControlPlaneService";
    impl<T> tonic::server::NamedService for ControlPlaneServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
