// This file is @generated by prost-build.
/// Describes how data is distributed across workers.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Distribution {
    #[prost(oneof = "distribution::DistributionType", tags = "1, 2, 3, 4")]
    pub distribution_type: ::core::option::Option<distribution::DistributionType>,
}
/// Nested message and enum types in `Distribution`.
pub mod distribution {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum DistributionType {
        #[prost(message, tag = "1")]
        Singleton(super::SingletonDistribution),
        #[prost(message, tag = "2")]
        HashPartitioned(super::HashPartitionedDistribution),
        #[prost(message, tag = "3")]
        EpochPartitioned(super::EpochPartitionedDistribution),
        #[prost(message, tag = "4")]
        Replicated(super::ReplicatedDistribution),
    }
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingletonDistribution {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HashPartitionedDistribution {
    /// Field indices into the schema (Substrait convention)
    #[prost(uint32, repeated, tag = "1")]
    pub field_refs: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, repeated, tag = "2")]
    pub worker_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpochPartitionedDistribution {
    #[prost(string, repeated, tag = "1")]
    pub worker_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicatedDistribution {
    #[prost(string, repeated, tag = "1")]
    pub worker_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Defines how data moves between stages.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Exchange {
    #[prost(oneof = "exchange::ExchangeType", tags = "1, 2, 3")]
    pub exchange_type: ::core::option::Option<exchange::ExchangeType>,
}
/// Nested message and enum types in `Exchange`.
pub mod exchange {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ExchangeType {
        #[prost(message, tag = "1")]
        Gather(super::GatherExchange),
        #[prost(message, tag = "2")]
        Broadcast(super::BroadcastExchange),
        #[prost(message, tag = "3")]
        HashPartition(super::HashPartitionExchange),
    }
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GatherExchange {
    #[prost(string, tag = "1")]
    pub target_worker_id: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BroadcastExchange {
    #[prost(string, repeated, tag = "1")]
    pub target_worker_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HashPartitionExchange {
    #[prost(uint32, repeated, tag = "1")]
    pub field_refs: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "2")]
    pub partitions: u32,
}
/// Describes how a stage receives its input data.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StageInput {
    #[prost(oneof = "stage_input::InputType", tags = "1, 2")]
    pub input_type: ::core::option::Option<stage_input::InputType>,
}
/// Nested message and enum types in `StageInput`.
pub mod stage_input {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum InputType {
        #[prost(message, tag = "1")]
        LocalCatalog(super::LocalCatalogInput),
        #[prost(message, tag = "2")]
        Exchange(super::ExchangeInput),
    }
}
/// Empty - indicates reading from local DuckDB catalog
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LocalCatalogInput {}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeInput {
    #[prost(uint32, tag = "1")]
    pub exchange_id: u32,
    /// Table name to register the exchange data as (e.g., "__exchange_0")
    #[prost(string, tag = "2")]
    pub table_name: ::prost::alloc::string::String,
}
/// Describes the output format of a stage.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StageOutput {
    #[prost(oneof = "stage_output::OutputType", tags = "1, 2")]
    pub output_type: ::core::option::Option<stage_output::OutputType>,
}
/// Nested message and enum types in `StageOutput`.
pub mod stage_output {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum OutputType {
        #[prost(message, tag = "1")]
        Stream(super::StreamOutput),
        #[prost(message, tag = "2")]
        Partitioned(super::PartitionedOutput),
    }
}
/// Empty - single Arrow stream
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamOutput {}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PartitionedOutput {
    #[prost(uint32, tag = "1")]
    pub partitions: u32,
}
/// Resource limits for stage execution.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StageLimits {
    #[prost(uint64, tag = "1")]
    pub max_bytes_output: u64,
    #[prost(uint64, tag = "2")]
    pub max_rows_output: u64,
    #[prost(uint64, tag = "3")]
    pub timeout_ms: u64,
    #[prost(uint64, tag = "4")]
    pub memory_bytes: u64,
}
/// A single execution stage in the LDP plan.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stage {
    #[prost(uint32, tag = "1")]
    pub stage_id: u32,
    #[prost(string, repeated, tag = "2")]
    pub target_worker_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub inputs: ::prost::alloc::vec::Vec<StageInput>,
    #[prost(message, optional, tag = "4")]
    pub output: ::core::option::Option<StageOutput>,
    /// Substrait plan fragment (serialized Substrait protobuf)
    #[prost(bytes = "vec", tag = "5")]
    pub substrait_plan: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub limits: ::core::option::Option<StageLimits>,
}
/// Represents data flow between two stages via an exchange.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeEdge {
    #[prost(uint32, tag = "1")]
    pub exchange_id: u32,
    #[prost(message, optional, tag = "2")]
    pub kind: ::core::option::Option<Exchange>,
    #[prost(uint32, tag = "3")]
    pub from_stage_id: u32,
    #[prost(uint32, tag = "4")]
    pub to_stage_id: u32,
    /// For HashPartition: partition index -> worker ID
    #[prost(string, repeated, tag = "5")]
    pub partition_to_worker: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// The complete Leibrix Distributed Plan for a query.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LdpPlan {
    #[prost(string, tag = "1")]
    pub query_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub coordinator_worker_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub stages: ::prost::alloc::vec::Vec<Stage>,
    #[prost(message, repeated, tag = "4")]
    pub edges: ::prost::alloc::vec::Vec<ExchangeEdge>,
}
/// Request to execute a stage on a worker.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitStageRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub query_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub stage_id: u32,
    /// The Substrait plan fragment to execute
    #[prost(bytes = "vec", tag = "4")]
    pub substrait_plan: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub limits: ::core::option::Option<StageLimits>,
    /// Exchange inputs to register before execution
    #[prost(message, repeated, tag = "6")]
    pub exchange_inputs: ::prost::alloc::vec::Vec<ExchangeInputRegistration>,
}
/// Information about an exchange input that needs to be registered.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeInputRegistration {
    /// Table name to register as (e.g., "__exchange_0")
    #[prost(string, tag = "1")]
    pub table_name: ::prost::alloc::string::String,
    /// Schema of the Arrow data (IPC format)
    #[prost(bytes = "vec", tag = "2")]
    pub arrow_schema: ::prost::alloc::vec::Vec<u8>,
}
/// Response from stage execution.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitStageResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    /// Ticket to retrieve results via DoGet
    #[prost(bytes = "vec", tag = "3")]
    pub result_ticket: ::prost::alloc::vec::Vec<u8>,
    /// Execution statistics
    #[prost(message, optional, tag = "4")]
    pub stats: ::core::option::Option<StageExecutionStats>,
}
/// Execution statistics for a stage.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StageExecutionStats {
    #[prost(uint64, tag = "1")]
    pub rows_produced: u64,
    #[prost(uint64, tag = "2")]
    pub bytes_produced: u64,
    #[prost(uint64, tag = "3")]
    pub execution_time_ms: u64,
}
/// Configuration for the LDP planner's cost-based decisions.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlannerPolicy {
    /// Max bytes for broadcast exchange (default: 256MB)
    #[prost(uint64, tag = "1")]
    pub broadcast_bytes_max: u64,
    /// Max bytes for shuffle exchange (default: 2GB)
    #[prost(uint64, tag = "2")]
    pub shuffle_bytes_max: u64,
    /// Max rows to gather (default: 50M)
    #[prost(uint64, tag = "3")]
    pub gather_rows_max: u64,
    /// Max bytes to gather (default: 5GB)
    #[prost(uint64, tag = "4")]
    pub gather_bytes_max: u64,
    /// Default number of hash partitions (default: 16)
    #[prost(uint32, tag = "5")]
    pub default_partitions: u32,
}
/// Statistics for an epoch, used for cost estimation.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpochStats {
    #[prost(uint64, tag = "1")]
    pub rows: u64,
    #[prost(uint64, tag = "2")]
    pub bytes: u64,
    /// Column name -> estimated NDV (number of distinct values)
    #[prost(map = "string, uint64", tag = "3")]
    pub ndv: ::std::collections::HashMap<::prost::alloc::string::String, u64>,
}
