//! Generated protocol buffer code.

pub mod common;
pub mod control_plane;
pub mod ldp;
pub mod google {
    pub mod protobuf {
        // this file is generated by tonic_build in out_dir
        include!("google.protobuf.rs");
    }
}
