[package]
name = "worker-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "liebrix-worker"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "env"] }
anyhow = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
worker-cp = { path = "../worker-cp" }
worker-flight = { path = "../worker-flight" }
worker-proto = { path = "../worker-proto" }
worker-storage = { path = "../worker-storage" }
