// This file is @generated by prost-build.
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Catalog {
    #[prost(oneof = "catalog::CatalogType", tags = "1, 2, 3")]
    pub catalog_type: ::core::option::Option<catalog::CatalogType>,
}
/// Nested message and enum types in `Catalog`.
pub mod catalog {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum CatalogType {
        #[prost(message, tag = "1")]
        Iceberg(super::IcebergCatalog),
        #[prost(message, tag = "2")]
        Starrocks(super::StarRocksCatalog),
        #[prost(message, tag = "3")]
        Jdbc(super::JdbcCatalog),
    }
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IcebergCatalog {
    #[prost(string, tag = "1")]
    pub uri: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StarRocksCatalog {
    #[prost(string, tag = "1")]
    pub dsn: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub internal_catalog_name: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JdbcCatalog {
    #[prost(string, tag = "1")]
    pub uri: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub driver: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Partition {
    /// REQUIRED: Time partition definition (first-class citizen)
    #[prost(message, optional, tag = "1")]
    pub time_partition: ::core::option::Option<TimePartition>,
    /// OPTIONAL: Additional dimension partitions (e.g., country, region, product_id)
    #[prost(message, repeated, tag = "2")]
    pub dimension_partitions: ::prost::alloc::vec::Vec<DimensionPartition>,
}
/// Time partition is mandatory and treated specially
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimePartition {
    /// The partition column definition
    #[prost(message, optional, tag = "1")]
    pub column: ::core::option::Option<PartitionColumn>,
    /// The time range to query
    #[prost(message, optional, tag = "2")]
    pub filter: ::core::option::Option<TimeRangeFilter>,
}
/// Additional dimension partitions (optional)
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DimensionPartition {
    /// The partition column definition
    #[prost(message, optional, tag = "1")]
    pub column: ::core::option::Option<PartitionColumn>,
    /// The partition values to filter
    #[prost(message, optional, tag = "2")]
    pub values: ::core::option::Option<PartitionValues>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartitionColumn {
    /// Column name (e.g., "dt", "event_date", "country")
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "partition_column::Type", tag = "2")]
    pub r#type: i32,
    #[prost(enumeration = "partition_column::Granularity", optional, tag = "3")]
    pub source_granularity: ::core::option::Option<i32>,
}
/// Nested message and enum types in `PartitionColumn`.
pub mod partition_column {
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Unknown = 0,
        Timestamp = 1,
        Date = 2,
        String = 3,
        Int64 = 4,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Timestamp => "TIMESTAMP",
                Self::Date => "DATE",
                Self::String => "STRING",
                Self::Int64 => "INT64",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "TIMESTAMP" => Some(Self::Timestamp),
                "DATE" => Some(Self::Date),
                "STRING" => Some(Self::String),
                "INT64" => Some(Self::Int64),
                _ => None,
            }
        }
    }
    /// For time-based partitions: the granularity of the source data
    /// This describes how the source table is partitioned, not how we group it
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Granularity {
        Unspecified = 0,
        Hour = 1,
        Day = 2,
        Week = 3,
        Month = 4,
    }
    impl Granularity {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "GRANULARITY_UNSPECIFIED",
                Self::Hour => "GRANULARITY_HOUR",
                Self::Day => "GRANULARITY_DAY",
                Self::Week => "GRANULARITY_WEEK",
                Self::Month => "GRANULARITY_MONTH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "GRANULARITY_UNSPECIFIED" => Some(Self::Unspecified),
                "GRANULARITY_HOUR" => Some(Self::Hour),
                "GRANULARITY_DAY" => Some(Self::Day),
                "GRANULARITY_WEEK" => Some(Self::Week),
                "GRANULARITY_MONTH" => Some(Self::Month),
                _ => None,
            }
        }
    }
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TimeRangeFilter {
    #[prost(message, optional, tag = "1")]
    pub start_inclusive: ::core::option::Option<super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end_exclusive: ::core::option::Option<super::google::protobuf::Timestamp>,
}
/// A list of partition values
/// If values contain duplicates, they map to the same partition (idempotent)
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartitionValues {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataSource {
    #[prost(message, optional, tag = "1")]
    pub catalog: ::core::option::Option<Catalog>,
    #[prost(string, tag = "2")]
    pub database: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub table: ::prost::alloc::string::String,
    /// REQUIRED: Partition specification with time as first-class citizen
    #[prost(message, optional, tag = "4")]
    pub partition: ::core::option::Option<Partition>,
    /// For snapshot-capable sources (e.g., Iceberg snapshot_id)
    #[prost(string, optional, tag = "5")]
    pub version: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TimeRange {
    #[prost(message, optional, tag = "1")]
    pub start_inclusive: ::core::option::Option<super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end_exclusive: ::core::option::Option<super::google::protobuf::Timestamp>,
}
/// Metadata about an epoch created by the admission request
/// This is synchronous - just the epoch metadata, not actual data stats
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpochInfo {
    /// Time-sortable epoch identifier
    /// Format: {start_timestamp_ms}_{hash_suffix}
    /// Example: "1730419200000_a7b3c2" for 2025-10-25
    /// This epoch_id will become the table name suffix in DuckDB:
    /// {dataset_id}_{epoch_id}
    #[prost(string, tag = "1")]
    pub epoch_id: ::prost::alloc::string::String,
    /// The time range this epoch covers
    #[prost(message, optional, tag = "2")]
    pub time_range: ::core::option::Option<TimeRange>,
    /// Additional partition dimensions (if any)
    #[prost(map = "string, string", tag = "3")]
    pub dimension_values: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpochInfoList {
    #[prost(message, repeated, tag = "1")]
    pub epochs: ::prost::alloc::vec::Vec<EpochInfo>,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EpochGranularity {
    /// Number of time units (must be > 0)
    /// Examples: 1, 3, 7, 10, 24, 72
    #[prost(int32, tag = "1")]
    pub value: i32,
    #[prost(enumeration = "epoch_granularity::TimeUnit", tag = "2")]
    pub unit: i32,
}
/// Nested message and enum types in `EpochGranularity`.
pub mod epoch_granularity {
    /// Time unit
    #[allow(non_camel_case_types)]
    #[allow(clippy::large_enum_variant)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum TimeUnit {
        Hour = 0,
        Day = 1,
        Week = 2,
        Month = 3,
    }
    impl TimeUnit {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Hour => "HOUR",
                Self::Day => "DAY",
                Self::Week => "WEEK",
                Self::Month => "MONTH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "HOUR" => Some(Self::Hour),
                "DAY" => Some(Self::Day),
                "WEEK" => Some(Self::Week),
                "MONTH" => Some(Self::Month),
                _ => None,
            }
        }
    }
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonResponse {
    #[prost(enumeration = "ResponseStatus", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseStatus {
    Unknown = 0,
    Success = 1,
    Error = 2,
}
impl ResponseStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Success => "SUCCESS",
            Self::Error => "ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "SUCCESS" => Some(Self::Success),
            "ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
