// This module contains the generated protobuf code
pub mod common;
pub mod control_plane;
pub mod google {
    pub mod protobuf {
        // this file is generated by tonic_build in out_dir
        include!("google.protobuf.rs");
    }
}
